inline const char arkanoid_level0[] =
"           \n"
"           \n"
"           \n"
" ABCDEFGHI \n"
" ABCDEFGHI \n"
" ABCDEFGHI \n"
" ABCDEFGHI \n"
" ABCDEFGHI \n"
" ABCDEFGHI \n"
" ABCDEFGHI \n"
" ######### \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
;

inline const char arkanoid_level1[] =
"           \n"
"           \n"
"           \n"
"IJKLMNOABCD\n"
"KJIHGFEDCBA\n"
"###########\n"
"IJKLMNOABCD\n"
"KJIHGFEDCBA\n"
"KJIHGFEDCBA\n"
"@ @ @ @ @ @\n"
"ABCDEFEDCBA\n"
"ABCDEFEDCBA\n"
"###########\n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
;

inline const char arkanoid_level2[] =
"           \n"
"           \n"
"           \n"
"     E     \n"
"    DDD    \n"
"   CCCCC   \n"
"  BBBBBBB  \n"
" AAAAAAAAA \n"
"@@#######@@\n"
" FFFFFFFFF \n"
"  GGGGGGG  \n"
"   HHHHH   \n"
"    III    \n"
"     J     \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
;

inline const char* const arkanoid_levels[]
{
	arkanoid_level0,
	arkanoid_level1,
	arkanoid_level2,
};

inline const char arkanoid_level_tetris_transition[] =
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"          F\n"
"          G\n"
"     A    G\n"
"  C  A#   A\n"
"  DEAB# B A\n"
"##CDEEF#DEA\n"
"ABCEEF#ABCD\n"
"FECF##DEABA\n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
"           \n"
;
